version: '3'

services:
  # App Python Utenti
  apputenti:
    build:
      context: utenti/program/
      dockerfile: Dockerfile
    volumes:
        - ./utenti/program:/app/logs
    container_name: apputenti
    restart: on-failure
    image: ergiacky/microservices:Apputenti
    command: sh -c "sleep 45s ; python3 ./app.py"
    ports:
      - '5000:5000'
    depends_on:
      - dbutenti
    networks:
      - users

  # DB Utenti MySQL
  dbutenti:
    build:
      context: utenti/db/
      dockerfile: Dockerfile
    container_name: dbutenti
    image: ergiacky/microservices:Dbutenti
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Utenti
      MYSQL_USER: sa
      MYSQL_PASSWORD: password 
    networks:
      - users


  # DB Libri MySQL
  dblibri:
    build:
      context: libri/db/
      dockerfile: Dockerfile
    container_name: dblibri
    image: ergiacky/microservices:Dblibri 
    restart: on-failure 
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Libri
      MYSQL_USER: sa
      MYSQL_PASSWORD: password  
    networks:
      - books

      # DB prestiti MySQL
  dbprestiti:
    build:
      context: prestiti/db/
      dockerfile: Dockerfile
    container_name: dbprestiti
    image: ergiacky/microservices:Dbprestiti
    restart: on-failure 
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Prestito
      MYSQL_USER: sa
      MYSQL_PASSWORD: password  
    networks:
      - borrowings

  # App Python Libri
  applibri:
    build:
      context: libri/program/
      dockerfile: Dockerfile
    volumes:
        - ./libri/program:/app/logs
    container_name: applibri
    restart: on-failure
    image: ergiacky/microservices:Applibri
    command: sh -c "sleep 45 ; python3 ./app.py"
    ports:
      - '4999:5000'
    depends_on:
      - dblibri 
    networks:
      - books 

  # App Python Prestiti
  appprestiti:
    build: 
      context: prestiti/program/
      dockerfile: Dockerfile
    volumes:
        - ./prestiti/program:/app/logs
    container_name: appPrestiti
    restart: on-failure
    image: ergiacky/microservices:Appprestiti
    command: sh -c "sleep 45 ; python3 ./app.py"
    ports:
      - 4998:5000
    networks:
      - borrowings

networks:
  users:
    driver: bridge
  books:
    driver: bridge
  borrowings:
    driver: bridge
