name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -  
        name: build and push db 
        uses: docker/build-push-action@v5
        with:
          context: .
          file: libri/db/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/libridb:latest

      -  
        name: build and push program
        uses: docker/build-push-action@v5
        with:
          context: .
          file: libri/program/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/libriprogram:latest

      -  
        name: build and push db 
        uses: docker/build-push-action@v5
        with:
          context: .
          file: utenti/db/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/utentidb:latest

      -  
        name: build and push db 
        uses: docker/build-push-action@v5
        with:
          context: .
          file: utenti/program/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/utentiprogram:latest
